// Code generated by goplus from node.gp. DO NOT EDIT.
//goplus:v v0.28.0

package taskrc

import (
	"goforge.dev/gptask/internal/fsext"
)

type Node struct {
	entrypoint string
}

func NewNode(
	entrypoint string,
	dir string,
	possibleFileNames []string,
) (*Node, error) {
	dir = fsext.DefaultDir(entrypoint, dir)
	resolvedEntrypoint, err := fsext.SearchPath(dir, possibleFileNames)
	if err != nil {
		return nil, err
	}
	return &Node{
		entrypoint: resolvedEntrypoint,
	}, nil
}
