// Code generated by goplus from pattern.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package gitignore implements gitignore pattern matching.
//
// This package is vendored from go-git:
//
//	github.com/go-git/go-git/v5 v5.19.1, plumbing/format/gitignore
//
// Only the pattern parsing and matching logic (pattern.go and matcher.go) is
// copied; the file-walking helpers (dir.go) are omitted as they pull in
// go-billy and other go-git internals. The original code is licensed under the
// Apache License 2.0; see the LICENSE file in this directory.
package gitignore

import (
	"path/filepath"
	"strings"
)

// MatchResult defines outcomes of a match, no match, exclusion or inclusion.
// A closed three-way sum expressed as a Go+ enum so every consumer must handle
// all three outcomes via match rather than relying on the historical int
// ordering (NoMatch<Exclude<Include). The result never crosses a wire boundary
// — it is consumed only inside this package (Matcher.Match) — so no ordinal or
// string projection is required.
//
//goplus:enum MatchResult
type MatchResult interface{ isMatchResult() }

// NoMatch defines the no match outcome of a match check
//
//goplus:variant (MatchResult) NoMatch
type NoMatch struct{}

func (NoMatch) isMatchResult() {}

// Exclude defines an exclusion of a file as a result of a match check
//
//goplus:variant (MatchResult) Exclude
type Exclude struct{}

func (Exclude) isMatchResult() {}

// Include defines an explicit inclusion of a file as a result of a match check
//
//goplus:variant (MatchResult) Include
type Include struct{}

func (Include) isMatchResult() {}

// MatchResultCases selects one handler per MatchResult variant for Fold.
type MatchResultCases[R any] struct {
	NoMatch func() R
	Exclude func() R
	Include func() R
}

// Fold reduces MatchResult by one-level case analysis.
func Fold[R any](m MatchResult, cs MatchResultCases[R]) R {
	switch any(m).(type) {
	case NoMatch:
		return cs.NoMatch()
	case Exclude:
		return cs.Exclude()
	case Include:
		return cs.Include()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// MatchResultEqOverrides carries optional per-variant hooks for MatchResultEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type MatchResultEqOverrides struct {
	NoMatch func(x, y NoMatch) (eq, handled bool)
	Exclude func(x, y Exclude) (eq, handled bool)
	Include func(x, y Include) (eq, handled bool)
}

// MatchResultEqualWith reports structural equality of a and b under ov.
func MatchResultEqualWith(a, b MatchResult, ov MatchResultEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NoMatch:
		y, ok := any(b).(NoMatch)
		if !ok {
			return false
		}
		if ov.NoMatch != nil {
			if eq, handled := ov.NoMatch(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Exclude:
		y, ok := any(b).(Exclude)
		if !ok {
			return false
		}
		if ov.Exclude != nil {
			if eq, handled := ov.Exclude(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Include:
		y, ok := any(b).(Include)
		if !ok {
			return false
		}
		if ov.Include != nil {
			if eq, handled := ov.Include(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// MatchResultEqual reports structural equality of a and b.
func MatchResultEqual(a, b MatchResult) bool {
	return MatchResultEqualWith(a, b, MatchResultEqOverrides{})
}

const (
	inclusionPrefix = "!"
	zeroToManyDirs  = "**"
	patternDirSep   = "/"
)

// Pattern defines a single gitignore pattern.
type Pattern interface {
	// Match matches the given path to the pattern.
	Match(path []string, isDir bool) MatchResult
}

type pattern struct {
	domain    []string
	pattern   []string
	inclusion bool
	dirOnly   bool
	isGlob    bool
}

// ParsePattern parses a gitignore pattern string into the Pattern structure.
func ParsePattern(p string, domain []string) Pattern {
	// storing domain, copy it to ensure it isn't changed externally
	domain = append([]string(nil), domain...)
	res := pattern{domain: domain}

	if strings.HasPrefix(p, inclusionPrefix) {
		res.inclusion = true
		p = p[1:]
	}

	if !strings.HasSuffix(p, "\\ ") {
		p = strings.TrimRight(p, " ")
	}

	if strings.HasSuffix(p, patternDirSep) {
		res.dirOnly = true
		p = p[:len(p)-1]
	}

	if strings.Contains(p, patternDirSep) {
		res.isGlob = true
	}

	res.pattern = strings.Split(p, patternDirSep)
	return &res
}

func (p *pattern) Match(path []string, isDir bool) MatchResult {
	if len(path) <= len(p.domain) {
		return NoMatch{}
	}
	for i, e := range p.domain {
		if path[i] != e {
			return NoMatch{}
		}
	}

	path = path[len(p.domain):]
	if p.isGlob && !p.globMatch(path, isDir) {
		return NoMatch{}
	} else if !p.isGlob && !p.simpleNameMatch(path, isDir) {
		return NoMatch{}
	}

	if p.inclusion {
		return Include{}
	} else {
		return Exclude{}
	}
}

func (p *pattern) simpleNameMatch(path []string, isDir bool) bool {
	for i, name := range path {
		if match, err := filepath.Match(p.pattern[0], name); err != nil {
			return false
		} else if !match {
			continue
		}
		if p.dirOnly && !isDir && i == len(path)-1 {
			return false
		}
		return true
	}
	return false
}

func (p *pattern) globMatch(path []string, isDir bool) bool {
	matched := false
	canTraverse := false
	for i, pattern := range p.pattern {
		if pattern == "" {
			canTraverse = false
			continue
		}
		if pattern == zeroToManyDirs {
			if i == len(p.pattern)-1 {
				break
			}
			canTraverse = true
			continue
		}
		if strings.Contains(pattern, zeroToManyDirs) {
			return false
		}
		if len(path) == 0 {
			return false
		}
		if canTraverse {
			canTraverse = false
			for len(path) > 0 {
				e := path[0]
				path = path[1:]
				if match, err := filepath.Match(pattern, e); err != nil {
					return false
				} else if match {
					matched = true
					break
				} else if len(path) == 0 {
					// if nothing left then fail
					matched = false
				}
			}
		} else {
			if match, err := filepath.Match(pattern, path[0]); err != nil || !match {
				return false
			}
			matched = true
			path = path[1:]
		}
	}
	if matched && p.dirOnly && !isDir && len(path) == 0 {
		matched = false
	}
	return matched
}
