// Code generated by goplus from interleaved.gp. DO NOT EDIT.
//goplus:v v0.28.0

package output

import (
	"io"

	"goforge.dev/gptask/internal/templater"
)

type Interleaved struct{}

func (Interleaved) WrapWriter(stdOut, stdErr io.Writer, _ string, _ *templater.Cache) (io.Writer, io.Writer, CloseFunc) {
	return stdOut, stdErr, func(error) error { return nil }
}
