// Code generated by goplus from devnull.gp. DO NOT EDIT.
//goplus:v v0.28.0

package execext

import (
	"io"
)

var _ io.ReadWriteCloser = devNull{}

type devNull struct{}

func (devNull) Read(p []byte) (int, error)  { return 0, io.EOF }
func (devNull) Write(p []byte) (int, error) { return len(p), nil }
func (devNull) Close() error                { return nil }
